### ISSUE TITLE
Updated 1.18 PonderJS doesn't reference correct Create dependency

### ISSUE THREAD

**Issue by logan-mcduffie** [Create-Additions/PonderMaker#6]
Game crashes on startup and claims it's missing the Create dependency. After this happened I went and made a separate profile and loaded only the bare minimum mods to run this, and I still run into the same issue. Here is the log file:

```
[17:19:03] [main/INFO]: ModLauncher running: args [--username, Meninism, --version, forge-39.0.7, --gameDir, C:\Users\logan\curseforge\minecraft\Instances\test, --assetsDir, C:\Users\logan\curseforge\minecraft\Install\assets, --assetIndex, 1.18, --uuid, f713f43190c8421d89a6c702ca992bc1, --accessToken, ????????, --clientId, MGJhZDQ3MDEtZTc0Ni00MmYxLTliZTktNzczODZiNGY5MGZl, --xuid, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 39.0.7, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407]
[17:19:03] [main/INFO]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 17.0.1 by Microsoft
[17:19:04] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/logan/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319! Service=ModLauncher Env=CLIENT
[17:19:04] [main/WARN]: Configuration file C:\Users\logan\curseforge\minecraft\Instances\test\config\fml.toml is not correct. Correcting
[17:19:04] [main/WARN]: Incorrect key [defaultConfigPath] was corrected from null to defaultconfigs
[17:19:04] [main/INFO]: Found mod file architectury-3.2.51.jar of type MOD with locator {mods folder locator at C:\Users\logan\curseforge\minecraft\Instances\test\mods}
[17:19:04] [main/INFO]: Found mod file create-mc1.18.1_v0.4a.jar of type MOD with locator {mods folder locator at C:\Users\logan\curseforge\minecraft\Instances\test\mods}
[17:19:04] [main/INFO]: Found mod file flywheel-forge-1.18-0.4.2-rc.jar of type MOD with locator {mods folder locator at C:\Users\logan\curseforge\minecraft\Instances\test\mods}
[17:19:04] [main/INFO]: Found mod file kubejs-forge-1801.4.0-build.249.jar of type MOD with locator {mods folder locator at C:\Users\logan\curseforge\minecraft\Instances\test\mods}
[17:19:04] [main/INFO]: Found mod file ponderjs-1.18-1.0.4.jar of type MOD with locator {mods folder locator at C:\Users\logan\curseforge\minecraft\Instances\test\mods}
[17:19:04] [main/INFO]: Found mod file rhino-forge-1800.1.6-build.81.jar of type MOD with locator {mods folder locator at C:\Users\logan\curseforge\minecraft\Instances\test\mods}
[17:19:04] [main/INFO]: Found mod file fmlcore-1.18.1-39.0.7.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@69c43e48
[17:19:04] [main/INFO]: Found mod file javafmllanguage-1.18.1-39.0.7.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@69c43e48
[17:19:04] [main/INFO]: Found mod file mclanguage-1.18.1-39.0.7.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@69c43e48
[17:19:04] [main/INFO]: Found mod file client-1.18.1-20211210.034407-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@69c43e48
[17:19:04] [main/INFO]: Found mod file forge-1.18.1-39.0.7-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@69c43e48
[17:19:04] [main/ERROR]: Missing mandatory dependencies: create
[17:19:05] [main/INFO]: Compatibility level set to JAVA_17
[17:19:05] [main/INFO]: Launching target 'forgeclient' with arguments [--version, forge-39.0.7, --gameDir, C:\Users\logan\curseforge\minecraft\Instances\test, --assetsDir, C:\Users\logan\curseforge\minecraft\Install\assets, --uuid, f713f43190c8421d89a6c702ca992bc1, --username, Meninism, --assetIndex, 1.18, --accessToken, ????????, --clientId, MGJhZDQ3MDEtZTc0Ni00MmYxLTliZTktNzczODZiNGY5MGZl, --xuid, --userType, mojang, --versionType, release, --width, 1024, --height, 768]
[17:19:05] [main/WARN]: Reference map 'ponderjs.refmap.json' for ponderjs.mixins.json could not be read. If this is a development environment you can ignore this message
[17:19:05] [main/WARN]: Reference map 'rhino-forge-refmap.json' for rhino.mixins.json could not be read. If this is a development environment you can ignore this message
[17:19:11] [Render thread/WARN]: Assets URL 'union:/C:/Users/logan/curseforge/minecraft/Install/libraries/net/minecraft/client/1.18.1-20211210.034407/client-1.18.1-20211210.034407-srg.jar%2358!/assets/.mcassetsroot' uses unexpected schema
[17:19:11] [Render thread/WARN]: Assets URL 'union:/C:/Users/logan/curseforge/minecraft/Install/libraries/net/minecraft/client/1.18.1-20211210.034407/client-1.18.1-20211210.034407-srg.jar%2358!/data/.mcassetsroot' uses unexpected schema
[17:19:12] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:19:13] [Render thread/INFO]: Setting user: Meninism
[17:19:13] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
[17:19:14] [Render thread/INFO]: Loaded client.properties
[17:19:15] [Render thread/FATAL]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod §eponderjs§r requires §6create§r §o0.4 or above, and below 0.4a§r
§7Currently, §6create§r§7 is §o0.4a
	at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:64) ~[fmlcore-1.18.1-39.0.7.jar%2359!:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraftforge.fml.ModLoader.<init>(ModLoader.java:108) ~[fmlcore-1.18.1-39.0.7.jar%2359!:?]
	at net.minecraftforge.fml.ModLoader.get(ModLoader.java:140) ~[fmlcore-1.18.1-39.0.7.jar%2359!:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:106) ~[forge-1.18.1-39.0.7-universal.jar%2362!:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:127) ~[forge-1.18.1-39.0.7-universal.jar%2362!:?]
	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:106) ~[forge-1.18.1-39.0.7-universal.jar%2362!:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:458) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.7.jar%2323!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]
[17:19:16] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundLoadEvent to a broken mod state
[17:19:16] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Block to a broken mod state
[17:19:16] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Item to a broken mod state
[17:19:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ParticleFactoryRegisterEvent to a broken mod state
[17:19:17] [Render thread/INFO]: Narrator library for x64 successfully loaded
[17:19:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientReloadListenersEvent to a broken mod state
[17:19:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterLayerDefinitions to a broken mod state
[17:19:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterRenderers to a broken mod state
[17:19:19] [Render thread/INFO]: Failed to find module info for C:\Users\logan\curseforge\minecraft\Install\bin\eb31-1e8a-e59c-195c\lwjgl.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.util.NativeModuleLister.m_184673_(NativeModuleLister.java:62) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184666_(NativeModuleLister.java:48) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184683_(NativeModuleLister.java:132) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.CrashReportCategory.m_128165_(CrashReportCategory.java:83) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184679_(NativeModuleLister.java:131) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.client.main.Main.main(Main.java:177) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.7.jar%2323!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]
[17:19:19] [Render thread/INFO]: Failed to find module info for C:\Users\logan\curseforge\minecraft\Install\bin\eb31-1e8a-e59c-195c\jemalloc.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.util.NativeModuleLister.m_184673_(NativeModuleLister.java:62) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184666_(NativeModuleLister.java:48) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184683_(NativeModuleLister.java:132) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.CrashReportCategory.m_128165_(CrashReportCategory.java:83) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184679_(NativeModuleLister.java:131) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.client.main.Main.main(Main.java:177) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.7.jar%2323!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]
[17:19:19] [Render thread/INFO]: Failed to find module info for C:\Users\logan\curseforge\minecraft\Install\bin\eb31-1e8a-e59c-195c\glfw.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.util.NativeModuleLister.m_184673_(NativeModuleLister.java:62) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184666_(NativeModuleLister.java:48) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184683_(NativeModuleLister.java:132) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.CrashReportCategory.m_128165_(CrashReportCategory.java:83) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184679_(NativeModuleLister.java:131) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.client.main.Main.main(Main.java:177) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.7.jar%2323!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]
[17:19:19] [Render thread/INFO]: Failed to find module info for C:\Users\logan\curseforge\minecraft\Install\bin\eb31-1e8a-e59c-195c\lwjgl_opengl.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.util.NativeModuleLister.m_184673_(NativeModuleLister.java:62) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184666_(NativeModuleLister.java:48) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184683_(NativeModuleLister.java:132) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.CrashReportCategory.m_128165_(CrashReportCategory.java:83) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184679_(NativeModuleLister.java:131) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.client.main.Main.main(Main.java:177) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.7.jar%2323!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]
[17:19:19] [Render thread/INFO]: Failed to find module info for C:\Users\logan\curseforge\minecraft\Install\bin\eb31-1e8a-e59c-195c\lwjgl_stb.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.util.NativeModuleLister.m_184673_(NativeModuleLister.java:62) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184666_(NativeModuleLister.java:48) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184683_(NativeModuleLister.java:132) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.CrashReportCategory.m_128165_(CrashReportCategory.java:83) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184679_(NativeModuleLister.java:131) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.client.main.Main.main(Main.java:177) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.7.jar%2323!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]
[17:19:19] [Render thread/INFO]: Failed to find module info for C:\Users\logan\curseforge\minecraft\Install\bin\eb31-1e8a-e59c-195c\OpenAL.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.util.NativeModuleLister.m_184673_(NativeModuleLister.java:62) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184666_(NativeModuleLister.java:48) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184683_(NativeModuleLister.java:132) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.CrashReportCategory.m_128165_(CrashReportCategory.java:83) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184679_(NativeModuleLister.java:131) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.client.main.Main.main(Main.java:177) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.7.jar%2323!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]
[17:19:19] [Render thread/INFO]: Failed to find module info for C:\Users\logan\curseforge\minecraft\Install\bin\eb31-1e8a-e59c-195c\SAPIWrapper_x64.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.util.NativeModuleLister.m_184673_(NativeModuleLister.java:62) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184666_(NativeModuleLister.java:48) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184683_(NativeModuleLister.java:132) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.CrashReportCategory.m_128165_(CrashReportCategory.java:83) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.util.NativeModuleLister.m_184679_(NativeModuleLister.java:131) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at net.minecraft.client.main.Main.main(Main.java:177) ~[client-1.18.1-20211210.034407-srg.jar%2358!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.7.jar%2323!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]
```

**Comment by AxelTheModder** [comment]
"Found mod file create-mc1.18.1_v0.4**a**.jar of type MOD"
"Mod ponderjs requires create 0.4 or above, and **below** 0.4**a**"

**Comment by kotakotik22** [comment]
yes, you are trying to launch ponderjs for create 0.4 with create 0.4a

**Comment by Eforen** [comment]
Can you put the latest version of create it's compatible with in the filename or something?
